In [6]:
import numpy as np
array_to_sq = np.arange(0,1000)
%timeit array_to_sq ** 2

The slowest run took 38.20 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 4.61 µs per loop


In [10]:
arr = np.zeros(10,dtype=int)
arr, type(arr)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), numpy.ndarray)

In [12]:
np.linspace(0,10,12)

array([  0.        ,   0.90909091,   1.81818182,   2.72727273,
         3.63636364,   4.54545455,   5.45454545,   6.36363636,
         7.27272727,   8.18181818,   9.09090909,  10.        ])

In [16]:
a1=np.arange(0,10)
a2=np.arange(10,20)
a1,a2,a1+a2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28]))

In [26]:
arr2 = np.arange(0,20).reshape(5,4)
arr2, np.size(arr2,1)

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]), 4)

In [27]:
arr2[1,2]

6

In [32]:
arr2[1]

array([4, 5, 6, 7])

In [33]:
#retrive entire column, here we retrive column at index 2
arr2[1:3,2]

array([ 6, 10])

In [35]:
arr2<2

array([[ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]], dtype=bool)

In [38]:
#vectorize applies all items in array
def judge(x):
    return x>2

np.vectorize(judge)(arr2)

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [39]:
#boolean selection
bol1 = arr2<10
arr2[bol1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
#How many items are less than 10
np.sum(arr2<10)

10

In [44]:
arr1=np.arange(20,0,-1).reshape(5,4)
arr1<arr2


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [46]:
# all rows, choose columns in positions
arr2[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [47]:
arr2[[1,3],:]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [48]:
#flatten
arr2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [50]:
flt2=arr2.flatten()
flt2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [51]:
flt2.shape

(20,)

In [52]:
flt2.shape=(2,10)
flt2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [53]:
flt2.transpose()

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

In [55]:
np.vstack((arr2,arr2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [56]:
#same as np.hstack
np.concatenate((arr2,arr2),axis=1) # for vertical axis=0

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15],
       [16, 17, 18, 19, 16, 17, 18, 19]])

In [57]:
np.row_stack((arr2,arr2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [58]:
np.dstack((arr2,arr2))

array([[[ 0,  0],
        [ 1,  1],
        [ 2,  2],
        [ 3,  3]],

       [[ 4,  4],
        [ 5,  5],
        [ 6,  6],
        [ 7,  7]],

       [[ 8,  8],
        [ 9,  9],
        [10, 10],
        [11, 11]],

       [[12, 12],
        [13, 13],
        [14, 14],
        [15, 15]],

       [[16, 16],
        [17, 17],
        [18, 18],
        [19, 19]]])

In [60]:
np.vsplit(arr2,5) #seems unintuitive.

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [61]:
np.vsplit(arr2,[1,3])

[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [63]:
arr2.min()

0

In [64]:
arr2.argmax()

19

In [65]:
arr2.max(axis=0)

array([16, 17, 18, 19])

In [67]:
arr2.cumsum(),arr2.cumprod()

(array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
         91, 105, 120, 136, 153, 171, 190], dtype=int32),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32))

In [71]:
(arr2<3).any(),(arr2<10).all()

(True, False)

In [72]:
#ndim = total of dimensions
arr2.ndim

2